server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nobreak_export_files
    static_configs:
      - targets:
          - localhost
        labels:
          job: nobreak-export
          __path__: /data/metrics/nobreak-*.jsonl

    pipeline_stages:
      - json:
          expressions:
            device_id: device_id
            ts: ts
      - labels:
          device_id:
      - timestamp:
          source: ts
          format: RFC3339Nano
